# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
    AROSDOCBUILDDIR:  '$(AZBUILDPATH)/www' # Location builds are done in
    AZBUILDPATH: '$(Build.BinariesDirectory)' # workspace path
    AROSDOCSRCDIR: '$(system.defaultWorkingDirectory)' # Path to the source code

steps:
- script: |
    sudo apt-key adv --keyserver packages.microsoft.com --recv-keys B02C46DF417A0893
    sudo pip install --upgrade pip
    sudo pip install Pillow
  displayName: 'Installing AROS build dependencies'

  - script: |
      mkdir -p '$(AROSDOCBUILDDIR)'
      echo '##vso[task.prependpath]$(AROSDOCBUILDDIR)'
    displayName: 'Setup workspace'

- script: |
    $(AROSDOCSRCDIR)/build
    ls -l
  workingDirectory: '$(AROSDOCBUILDDIR)'
  displayName: 'Building website & documentation'

#- script: |
#    sshpass -p "$(MAPPED_PASS)" rsync -rciv --rsh=ssh /home/mazze/projects/aros-src/bin/documentation/www/ $(MAPPED_USER),aros@web.sourceforge.net:/home/project-web/aros/htdocs/
#  env:
#    MAPPED_USER: $(RSYNC_USER)
#    MAPPED_PASS: $(RSYNC_PASSWORD)
#  displayName: 'Deploying website'
